spring:
  application:
    name: pal-tracker
  datasource:
    platform: mysql
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"